import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import "./globals.css";
import ClientProviders from "@/components/ClientProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-google-sans">
        <Navbar />
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
